// Blog content for AnotherDev.
// Each post renders on /blog and at /blog/:slug. Keep copy factual and free of
// invented statistics. Note: no em dashes anywhere in this file.

export const posts = [
  {
    slug: 'how-to-install-anotherdev-shoppable-video',
    cat: 'Guides',
    date: 'Sep 25, 2026',
    read: '4 min',
    cover: '',
    title: 'How to install AnotherDev Shoppable Video on your Shopify store',
    excerpt: 'A quick, no-code walkthrough: add the app, enable it in your theme, and publish your first shoppable video in minutes.',
    content: [
      { type: 'p', text: 'Adding shoppable video to your Shopify store takes a few minutes and no theme code. Here is the full walkthrough, from install to your first live reel.' },
      { type: 'h2', text: 'Step 1: Add the app from the Shopify App Store' },
      { type: 'p', text: 'Open the listing at https://apps.shopify.com/another-shoppable-video-app , click Add app, choose your store, and approve. The Free plan needs no credit card, so you can start at no cost.' },
      { type: 'h2', text: 'Step 2: Enable it in your theme' },
      { type: 'p', text: 'In your Shopify admin, go to Online Store, then Themes, then Customize, and turn on the AnotherDev app embed. No theme code is required, and removing the app later leaves your theme exactly as it was.' },
      { type: 'h2', text: 'Step 3: Add your first video' },
      { type: 'p', text: 'Upload a product video or import one from your Shopify Files library, then link it to the product and the exact variant it shows. The card then displays that product with its live price and an Add to Cart button.' },
      { type: 'h2', text: 'Step 4: Place it on your store' },
      { type: 'p', text: 'In the theme editor, drop a block where you want it: a shoppable feed on the home page or a collection, a carousel on a product page, or a floating reel that follows shoppers. Most stores are live in under five minutes. See /how-it-works for the full guide.' },
      { type: 'h2', text: 'Prefer some help installing?' },
      { type: 'p', text: 'The app is also featured on services and directories that help merchants set up Shopify apps. Hura Apps has an installation guide and offers install help at https://www.huratips.com/shopify-services/shopify-app-installation.php?app=another-shoppable-video-app , and it is listed on PickYourApp at https://pickyourapp.com/products/another-shoppable-video-app . Either way, the app is free to start on the Shopify App Store.' },
      { type: 'p', text: 'Learn more about what the app does on /shoppable-video.' },
    ],
  },
  {
    slug: 'another-shoppable-video-on-pickyourapp',
    cat: 'News',
    date: 'Sep 25, 2026',
    read: '3 min',
    cover: 'post__cover--2',
    title: 'AnotherDev Shoppable Video is now on PickYourApp',
    excerpt: 'Our shoppable video app for Shopify is now listed on PickYourApp, a curated Shopify app directory. Here is what that means and where to find it.',
    content: [
      { type: 'p', text: 'AnotherDev Shoppable Video is now listed on PickYourApp, a directory where Shopify merchants discover and compare apps. You can view the listing here: https://pickyourapp.com/products/another-shoppable-video-app' },
      { type: 'h2', text: 'What is PickYourApp?' },
      { type: 'p', text: 'PickYourApp is a curated directory of Shopify apps, where merchants browse, compare, and install apps to improve their store. Being listed there gives merchants another place to find the app alongside the Shopify App Store.' },
      { type: 'h2', text: 'What the app does' },
      { type: 'p', text: 'AnotherDev Shoppable Video turns your product videos into a shoppable storefront. Shoppers watch a reel, tap the product card, and add to cart without leaving the page.' },
      { type: 'ul', items: [
        'Add to cart inside the video, using your theme’s own native cart.',
        'Smart tag matching that shows the right videos on the right products automatically.',
        'Video feeds and carousels for your home page, collections, and product pages, plus a floating reel.',
        'Real-time analytics: impressions, plays, clicks, and conversions.',
        'Import videos from your Shopify Files library or paste a video URL.',
      ] },
      { type: 'h2', text: 'Pricing' },
      { type: 'ul', items: [
        'Free: up to 4 videos with basic analytics.',
        'Growth: $21/mo for up to 21 videos with customization.',
        'Pro: $49/mo for up to 49 videos with advanced features.',
      ] },
      { type: 'p', text: 'The Free plan lets you start at no cost, and paid plans are billed through Shopify.' },
      { type: 'h2', text: 'Where to get it' },
      { type: 'p', text: 'Install it from the Shopify App Store at https://apps.shopify.com/another-shoppable-video-app , see the listing on PickYourApp at https://pickyourapp.com/products/another-shoppable-video-app , or read more on our own page at /shoppable-video' },
    ],
  },
  {
    slug: 'how-to-add-shoppable-video-to-shopify',
    cat: 'Guides',
    date: 'Jun 2, 2026',
    read: '6 min',
    cover: '',
    title: 'How to add shoppable video to your Shopify store',
    excerpt: 'A step by step guide to turning product videos into shoppable reels with in-video add to cart, no code required.',
    content: [
      { type: 'p', text: 'Shoppable video lets a customer watch a product in motion and add it to cart in the same moment, without leaving the page they are on. This guide walks through adding shoppable video to a Shopify store from start to finish, using AnotherDev.' },
      { type: 'h2', text: 'What you need before you start' },
      { type: 'p', text: 'You need a Shopify store on an Online Store 2.0 theme (Dawn and most modern themes qualify) and at least one product video. The video can be footage you already own, a clip from your Shopify Files library, or any hosted video URL. Vertical, short form clips in a 9:16 ratio work best.' },
      { type: 'h2', text: 'Step 1: Add a reel' },
      { type: 'p', text: 'In the app, create a reel by uploading a video, importing one from Shopify Files, or pasting a hosted URL. Then link the reel to the exact product variant shown in the clip, for example the specific color and size. That exact variant is what gets added to cart, so shoppers never end up with the wrong option.' },
      { type: 'p', text: 'You can also add an optional ribbon such as SALE, NEW, or BESTSELLER, which appears as a small tag on the reel card.' },
      { type: 'h2', text: 'Step 2: Place it on your storefront' },
      { type: 'p', text: 'Open the Shopify theme editor, enable the app embed, and drop a shoppable video block where you want it. You have a few options:' },
      { type: 'ul', items: [
        'A shoppable video feed for your home page or collection pages.',
        'A carousel in the product detail section that shows reels linked to that product.',
        'Smart tag reels that match a product automatically by its tags.',
      ] },
      { type: 'p', text: 'Style the card to match your brand: colors, fonts, corner radius, card height, and whether to show the title, price, and arrows. No theme code is required.' },
      { type: 'h2', text: 'Step 3: Sell and measure' },
      { type: 'p', text: 'Once published, shoppers watch the reel, tap Add to Cart on the in-video product card, and the item is added using your theme native cart. From there you can track impressions, plays, clicks, and add-to-cart events per reel, along with play rate, click-through rate, and conversion.' },
      { type: 'h2', text: 'Tips for a strong start' },
      { type: 'ul', items: [
        'Keep individual video files light (MP4, 9:16, under about 15 MB) so pages stay fast.',
        'Lead with your best sellers, since those reels tend to earn the most engagement.',
        'Check analytics after a week and promote the reels with the highest click-through rate.',
      ] },
    ],
  },
  {
    slug: 'shoppable-video-vs-product-photos',
    cat: 'Conversion',
    date: 'May 28, 2026',
    read: '5 min',
    cover: 'post__cover--2',
    title: 'Shoppable video vs static product photos: why video sells',
    excerpt: 'Photos show a product. Video shows how it looks, moves, and fits. Here is why shoppable video helps shoppers decide.',
    content: [
      { type: 'p', text: 'Static product photos do an important job, but they have a limit: they cannot show how a product looks in motion, how a fabric drapes, or how a size fits a real body. Shoppable video closes that gap, and it does it right where the shopper is deciding.' },
      { type: 'h2', text: 'Video answers the questions photos leave open' },
      { type: 'p', text: 'Most add-to-cart hesitation comes from uncertainty. Will this fit? How big is it really? What does it look like on? A short reel answers those questions in seconds, in a format shoppers already understand from social feeds.' },
      { type: 'h2', text: 'Shoppable video keeps the buying flow intact' },
      { type: 'p', text: 'A normal product video can build interest, but it often sends the shopper away to a separate player or a social platform. Shoppable video keeps everything on your storefront. The product card sits on top of the reel with the title, price, and an Add to Cart button, so interest turns into an order without a detour.' },
      { type: 'h2', text: 'You do not have to choose one or the other' },
      { type: 'p', text: 'The strongest product pages use both. Photos give the crisp, zoomable detail, and video gives the movement and context. Adding a reel to the product detail section, next to your gallery, lets each format do what it does best.' },
      { type: 'h2', text: 'Where to start' },
      { type: 'ul', items: [
        'Add a reel to your top selling product first and watch the analytics.',
        'Use real footage: worn, used, or demonstrated in context beats a static spin.',
        'Link the exact variant shown so the add to cart matches the video.',
      ] },
    ],
  },
  {
    slug: 'where-to-place-shoppable-video-on-shopify',
    cat: 'Strategy',
    date: 'May 14, 2026',
    read: '6 min',
    cover: 'post__cover--3',
    title: 'Where to place shoppable video on Shopify: home, product, and collections',
    excerpt: 'A practical map of shoppable video placements and when to use each one, from the home page feed to the product carousel.',
    content: [
      { type: 'p', text: 'Placement decides how much work a reel does. The same video can introduce your brand on the home page, or close a sale on a product page. Here is how to think about each placement.' },
      { type: 'h2', text: 'Home page: the shoppable video feed' },
      { type: 'p', text: 'A shoppable video feed on the home page works like a swipeable gallery that introduces first time visitors to your brand and best sellers. It auto-detects the page and shows the reels assigned to it. If a page has no reels of its own, it falls back to the home page reels, so the feed is never empty.' },
      { type: 'h2', text: 'Product pages: the carousel' },
      { type: 'p', text: 'On a product page, a carousel in the product detail section shows reels linked to that specific product. This is the highest intent placement, because the shopper is already considering the item. You can adjust the card height and choose a one or two card layout.' },
      { type: 'h2', text: 'Collections and other pages' },
      { type: 'p', text: 'Collection pages and other landing pages can carry a feed too, so category browsers see relevant video as they scroll. This keeps the experience consistent across the store rather than limiting video to a single page.' },
      { type: 'h2', text: 'Smart tag reels' },
      { type: 'p', text: 'Smart tag reels remove manual work by matching reels to a product automatically when the reel tag matches the product tags. You tag once and the right reels show up on the right products, with no per product linking.' },
      { type: 'h2', text: 'A simple placement plan' },
      { type: 'ul', items: [
        'Home page feed to introduce the brand and best sellers.',
        'Product carousel on your top revenue products to lift add to cart.',
        'Smart tag reels to scale coverage across a large catalog.',
      ] },
    ],
  },
  {
    slug: 'in-video-add-to-cart-explained',
    cat: 'Conversion',
    date: 'Apr 30, 2026',
    read: '4 min',
    cover: 'post__cover--2',
    title: 'In-video add to cart: how it works and why it matters',
    excerpt: 'The difference between a video that plays and a video that sells is one button. Here is how in-video add to cart works.',
    content: [
      { type: 'p', text: 'Plenty of apps can put a video on your storefront. The feature that turns a view into an order is in-video add to cart. Here is what it does and why it matters.' },
      { type: 'h2', text: 'What the shopper sees' },
      { type: 'p', text: 'A product card overlays the reel with the product title, price, compare-at price, and an Add to Cart button. One tap adds the item to cart without pausing the experience or opening a new page. Prices display in your store own currency automatically.' },
      { type: 'h2', text: 'Exact variant accuracy' },
      { type: 'p', text: 'When you build a reel, you link the specific variant shown in the video, such as Red in size M. That exact variant is what gets added to cart, and it is shown on the card. Shoppers do not have to guess or re-select, which removes a common point of friction.' },
      { type: 'h2', text: 'It uses your theme native cart' },
      { type: 'p', text: 'Add to cart plugs into your existing Shopify cart. It updates the theme cart drawer and item count automatically, and works across Dawn and Online Store 2.0 themes, premium themes such as Symmetry, and older vintage themes. It also works with third-party carts like GoKwik and Shiprocket, opening their cart rather than breaking it. Checkout stays exactly as your store already handles it.' },
      { type: 'h2', text: 'Why it matters' },
      { type: 'p', text: 'Every extra step between interest and purchase is a chance to lose the sale. By collapsing watch, decide, and add to cart into a single moment on a single page, in-video add to cart keeps momentum on the shopper side.' },
    ],
  },
  {
    slug: 'keep-shoppable-video-fast-core-web-vitals',
    cat: 'Performance',
    date: 'Apr 16, 2026',
    read: '5 min',
    cover: 'post__cover--3',
    title: 'Keep shoppable video fast: Core Web Vitals on Shopify',
    excerpt: 'Video does not have to slow your store down. Here is how to add shoppable reels while protecting your speed scores.',
    content: [
      { type: 'p', text: 'Speed is part of the shopping experience and part of how search engines rank pages. The good news is that shoppable video can be added without hurting Core Web Vitals, as long as it is built the right way.' },
      { type: 'h2', text: 'Load video only when it is needed' },
      { type: 'p', text: 'Videos should lazy-load, meaning they only start loading when they scroll into view. A reel near the bottom of a page should not compete for bandwidth with the content at the top. AnotherDev defers its scripts and lazy-loads video for this reason.' },
      { type: 'h2', text: 'Keep the footprint small' },
      { type: 'p', text: 'A heavy storefront widget is a hidden tax on every page load. The storefront bundle here is tiny, around 12 KB gzipped, and it is designed to avoid layout shift so content does not jump around as the page loads. That protects the Cumulative Layout Shift metric.' },
      { type: 'h2', text: 'Optimize the video files themselves' },
      { type: 'ul', items: [
        'Export in MP4 with a 9:16 ratio for vertical reels.',
        'Aim to keep each clip light, ideally under about 15 MB.',
        'Trim to the moments that matter rather than uploading long footage.',
      ] },
      { type: 'h2', text: 'Measure after you launch' },
      { type: 'p', text: 'Run a Lighthouse or PageSpeed check before and after adding reels. If a metric moves in the wrong direction, look at video file size first, since that is the most common cause.' },
    ],
  },
  {
    slug: 'turn-ugc-into-shoppable-reels',
    cat: 'UGC',
    date: 'Apr 3, 2026',
    read: '5 min',
    cover: 'post__cover--2',
    title: 'Turn UGC and creator clips into shoppable reels',
    excerpt: 'Customer and creator video is some of the most persuasive content you have. Here is how to make it shoppable.',
    content: [
      { type: 'p', text: 'User generated content and creator clips carry a trust that polished studio footage cannot always match. Turning that content into shoppable reels puts real, relatable video to work on your storefront.' },
      { type: 'h2', text: 'Source content you have the rights to use' },
      { type: 'p', text: 'Start with footage you own or have permission to use: customer clips shared with consent, creator content from a paid collaboration, or your own behind the scenes video. Always confirm rights before publishing someone else content.' },
      { type: 'h2', text: 'Bring it into the store' },
      { type: 'p', text: 'Import the clip from your Shopify Files library or paste a hosted video URL. Then link the reel to the exact product variant it features, so a shopper who loves the look can add that item in one tap.' },
      { type: 'h2', text: 'Keep it feeling native' },
      { type: 'p', text: 'Short form, vertical, mute by default reels match the format shoppers already know from social feeds. That familiarity is part of what makes UGC persuasive, so keep the editing light and the pacing quick.' },
      { type: 'h2', text: 'Build a repeatable workflow' },
      { type: 'ul', items: [
        'Collect clips continuously and get rights up front.',
        'Batch new reels on a schedule so the storefront stays fresh.',
        'Use ribbons like NEW to highlight recently added content.',
      ] },
    ],
  },
  {
    slug: 'choosing-a-shoppable-video-app-for-shopify',
    cat: 'Guides',
    date: 'Mar 20, 2026',
    read: '7 min',
    cover: 'post__cover--3',
    title: 'Choosing a shoppable video app for Shopify: what to look for',
    excerpt: 'A buyer checklist for shoppable video apps, covering add to cart, placements, speed, analytics, and privacy.',
    content: [
      { type: 'p', text: 'There are several ways to put video on a Shopify store, and they are not all equal. If you are comparing shoppable video apps, here are the things that actually matter once you get past the marketing.' },
      { type: 'h2', text: 'Real in-video add to cart' },
      { type: 'p', text: 'Look for true in-video add to cart that uses your theme native cart, not just a video that links out to a product page. The best experience adds the exact variant shown, in your store own currency, and updates the cart drawer automatically.' },
      { type: 'h2', text: 'Flexible placements' },
      { type: 'p', text: 'You want more than one place to show video. A home page feed introduces the brand, a product page carousel drives conversion, and automatic tag matching helps you scale across a large catalog without linking every product by hand.' },
      { type: 'h2', text: 'Speed and no code setup' },
      { type: 'p', text: 'Check that video lazy-loads, scripts are deferred, and the storefront footprint is small with no layout shift. Setup should happen through the Shopify theme editor with drag and drop blocks, so you are not editing theme files or waiting on a developer.' },
      { type: 'h2', text: 'Analytics you can act on' },
      { type: 'p', text: 'Impressions and plays are a start, but you also want clicks, add-to-cart events, and derived rates like play rate, click-through rate, and conversion, so you can tell which reels are actually earning their place.' },
      { type: 'h2', text: 'Privacy and billing' },
      { type: 'ul', items: [
        'Confirm the app requests only the permissions it needs and does not collect shopper personal data unnecessarily.',
        'Prefer billing handled through Shopify, so charges appear on your normal invoice.',
        'Make sure there is a free plan or trial so you can test before you commit.',
      ] },
      { type: 'p', text: 'AnotherDev is built around this checklist: in-video add to cart with exact variants, multiple placements, a lightweight and fast storefront widget, real time analytics, and a free plan billed through Shopify.' },
    ],
  },
  {
    slug: 'add-instant-search-to-shopify',
    cat: 'Search',
    date: 'Sep 2, 2026',
    read: '6 min',
    cover: 'post__cover--2',
    title: 'How to add instant search to your Shopify store',
    excerpt: 'Most theme search boxes only match titles. Here is how to add instant, typo-tolerant search that reads your whole catalog.',
    content: [
      { type: 'p', text: 'A theme’s built-in search usually matches the product title and little else. Shoppers who type a SKU, a material, or a slightly misspelled word get nothing. Instant search fixes that by building an index the app owns and querying it as the shopper types.' },
      { type: 'h2', text: 'Why the default search falls short' },
      { type: 'p', text: 'Default Shopify search is keyword matching over a narrow set of fields. It does not forgive typos, does not know your synonyms, and cannot filter results the way a shopper expects. On a large catalog, that means lost sales from people who could not find what they wanted.' },
      { type: 'h2', text: 'What instant search adds' },
      { type: 'ul', items: [
        'Results appear as the shopper types, not after they press enter.',
        'It searches descriptions, vendors, product types, tags, SKUs, variant names, options and metafields.',
        'Typo tolerance forgives misspellings, and synonyms map “tee” to “t-shirt”.',
        'Faceted filters let shoppers narrow the results by any attribute.',
      ] },
      { type: 'h2', text: 'How to set it up' },
      { type: 'p', text: 'Install AnotherDev Search and Filters, let it sync your catalog once, then enable the theme app block. Instant search upgrades your existing search box, and filters appear on your search and collection pages. No theme code, and it works with Dawn, premium themes, and older vintage themes.' },
    ],
  },
  {
    slug: 'faceted-filters-that-convert',
    cat: 'Search',
    date: 'Aug 26, 2026',
    read: '5 min',
    cover: 'post__cover--3',
    title: 'Faceted filters that actually help shoppers buy',
    excerpt: 'Filters are only useful if every option works and the layout fits the page. A short guide to getting them right.',
    content: [
      { type: 'p', text: 'Good filters turn a long results page into a short, relevant one. Bad filters show options that do nothing, or push the products off the screen. The difference is in which facets you expose and how you lay them out.' },
      { type: 'h2', text: 'Choose facets shoppers actually use' },
      { type: 'p', text: 'Start with the attributes people shop by: size, color, price, material, brand. Expose those as facets and leave the rest. Every facet should change the results, or it is just noise.' },
      { type: 'h2', text: 'Pick a layout that fits the page' },
      { type: 'ul', items: [
        'Sidebar: a column beside the grid, good for catalogs with many facets.',
        'Toolbar: dropdown buttons above the grid that float open, good for image-led stores.',
        'Drawer: a Filters button at every width, good on mobile-first stores.',
        'Always open: facets stacked above the grid when you want everything visible.',
      ] },
      { type: 'h2', text: 'Keep counts honest' },
      { type: 'p', text: 'Show the product count beside each value, and compute those counts from the same query that draws the grid, so the number always matches what the shopper will see. AnotherDev Search and Filters does this in a single request.' },
    ],
  },
  {
    slug: 'zero-result-searches',
    cat: 'Analytics',
    date: 'Aug 18, 2026',
    read: '4 min',
    cover: '',
    title: 'What zero-result searches are telling you',
    excerpt: 'A search that returns nothing is a shopper telling you what they wanted and could not find. Here is how to read them.',
    content: [
      { type: 'p', text: 'Zero-result searches are one of the most useful reports a store has. Each one is a shopper who wanted something specific enough to type it, and found nothing. Read them, and you learn what to stock, what to rename, and what synonyms to add.' },
      { type: 'h2', text: 'Three things they reveal' },
      { type: 'ul', items: [
        'Demand you do not stock yet: a product people keep searching for.',
        'Vocabulary gaps: shoppers use a word your catalog does not, which a synonym can fix.',
        'Catalog errors: a product exists but is mistagged or missing from the index.',
      ] },
      { type: 'h2', text: 'What to do about them' },
      { type: 'p', text: 'For vocabulary gaps, add a synonym so the shopper’s word finds the right product. For missing demand, consider stocking it or redirecting the term to a related collection. For catalog errors, fix the product data and re-sync. AnotherDev Search and Filters reports top searches and zero-result terms so you can act on them.' },
    ],
  },
  {
    slug: 'merchandising-search-results',
    cat: 'Merchandising',
    date: 'Aug 11, 2026',
    read: '5 min',
    cover: 'post__cover--2',
    title: 'Merchandising your search results: pin, boost, bury',
    excerpt: 'Relevance gets shoppers close. Merchandising puts the right products first. A practical look at controlling the order.',
    content: [
      { type: 'p', text: 'Search relevance decides which products match. Merchandising decides which of those come first. Both matter, and the second is where you put your margin, your new arrivals, and your best sellers in front of shoppers.' },
      { type: 'h2', text: 'The controls' },
      { type: 'ul', items: [
        'Pin: force a product to the top of a specific search term or collection.',
        'Boost: nudge a product up without forcing it to the very top.',
        'Bury: push a product down, for clearance or low-margin items.',
        'Hide: keep a product out of results entirely for a term.',
        'Redirect: send a term straight to a page, for campaigns or brand names.',
      ] },
      { type: 'h2', text: 'Use it with intent' },
      { type: 'p', text: 'Merchandise the terms that matter most first: your highest-volume searches and your key collections. Pin sparingly, so results still feel relevant, and revisit your rules when the season or the catalog changes.' },
    ],
  },
  {
    slug: 'site-search-conversion',
    cat: 'Conversion',
    date: 'Aug 4, 2026',
    read: '5 min',
    cover: 'post__cover--3',
    title: 'Why site search is a conversion lever, not a utility',
    excerpt: 'Shoppers who search convert at a higher rate, when search works. Treating it as a core part of the funnel pays off.',
    content: [
      { type: 'p', text: 'Search is easy to treat as plumbing: a box in the header that someone set up once. But shoppers who use search are telling you they have intent, and giving them fast, relevant results is one of the clearest ways to move the conversion needle.' },
      { type: 'h2', text: 'Searchers are high-intent' },
      { type: 'p', text: 'A shopper who types a query usually knows what they want. If the results are fast and relevant, you have removed the friction between intent and purchase. If they are slow, empty, or wrong, you have added it.' },
      { type: 'h2', text: 'What good search looks like' },
      { type: 'ul', items: [
        'Instant results, so the shopper never waits or leaves.',
        'Typo tolerance and synonyms, so near-misses still find products.',
        'Filters that let the shopper narrow a big result set quickly.',
        'Analytics, so you keep improving what shoppers search for.',
      ] },
      { type: 'h2', text: 'Measure it' },
      { type: 'p', text: 'Track search click-through and add-to-cart, and watch your zero-result terms. Treat search as part of the funnel, not a set-and-forget utility, and it becomes one of the highest-leverage things you can tune.' },
    ],
  },
];

export const getPost = (slug) => posts.find((p) => p.slug === slug);
